### ISSUE TITLE
CSS version

### ISSUE THREAD

**Issue by adamschwartz** [stefansundin/github-light-navbar#1]
Assuming the HTML doesn’t change when they remove the class name, here’s a future-proof CSS solution:

```CSS
.header.header-dark, .header  {
  color: #333;
  background-color: #f5f5f5;
  border-bottom: 1px solid #e5e5e5
}

.header-dark .read-only-mode-banner, .read-only-mode-banner  {
  background-color: #f8e45f;
  border-bottom-color: #f6dc2e
}

.header-dark .header-logo-invertocat, .header-dark .header-logo-wordmark, .header-logo-invertocat, .header-logo-wordmark  {
  color: #555
}

.header-dark .header-logo-invertocat:hover, .header-dark .header-logo-wordmark:hover, .header-logo-invertocat:hover, .header-logo-wordmark:hover  {
  color: #4078c0
}

.header-dark .notification-indicator .mail-status, .notification-indicator .mail-status  {
  color: #fff;
  background-image: -webkit-linear-gradient(#1cafff, #0086ce);
  background-image: linear-gradient(#1cafff, #0086ce);
  border: 2px solid #f3f3f3
}

.header-dark .notification-indicator:hover .mail-status, .notification-indicator:hover .mail-status  {
  background-color: #4078c0
}

.header-dark .header-search-scope, .header-search-scope  {
  color: #767676;
  border-right: 1px solid #eee;
}

.header-dark .scoped-search .form-control.focus .header-search-scope, .scoped-search .form-control.focus .header-search-scope  {
  color: #4078c0;
  background-color: #edf2f9;
  border-color: #c6d7ec
}

.header-dark .header-nav-link, .header-nav-link  {
  color: #555
}

.header-dark .header-nav-link:hover, .header-dark .header-nav-link:focus, .header-nav-link:hover, .header-nav-link:focus  {
  color: #4078c0
}

.header-dark .header-nav-link:hover .dropdown-caret, .header-dark .header-nav-link:focus .dropdown-caret, .header-nav-link:hover .dropdown-caret, .header-nav-link:focus .dropdown-caret  {
  border-top-color: #4078c0
}

.header-dark .header-search, .header-search  {
  font-size: 14px
}

.header-dark .header-search-wrapper, .header-search-wrapper  {
  background: #fff;
  box-shadow: inset 0 1px 2px rgba(0,0,0,0.075);
  border: 1px solid #ddd;
  font-size: 14px;
  min-height: 0;
}

.header-dark .header-search-wrapper.focus, .header-search-wrapper.focus  {
  background: #fff;
  border-color: #51a7e8;
  outline: none;
  color: inherit;
  box-shadow: inset 0 1px 2px rgba(0, 0, 0, .075), 0 0 5px rgba(81, 167, 232, .5);
}

.header-dark .header-search-scope, .header-search-scope  {
  font-size: 12px;
  line-height: inherit;
  min-height: 0;
}

.header-dark .header-search-input, .header-search-input  {
  min-height: 26px;
}

.header-dark .header-search-input::-webkit-input-placeholder, .header-search-input::-webkit-input-placeholder  {
  color: rgba(0,0,0,.5)
}

.header-dark .header-search-input::placeholder, .header-search-input::placeholder  {
  color: rgba(0,0,0,.5)
}
```
